services:
  - type: web
    name: vinayakamotorsadithi
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: vinayakamotorsadithi-api
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 22
